== PP Module for File Encryption Enterprise Management

[cols="1,1,1,1,1,1,1,1"]
|===
8+|fileencryption-enterprisemgmt
| https://github.com/commoncriteria/fileencryption-enterprisemgmt/tree/master[master] 
a| https://commoncriteria.github.io/fileencryption-enterprisemgmt/master/fileencryption-enterprisemgmt-release.html[📄]
a|[link=https://github.com/commoncriteria/fileencryption-enterprisemgmt/blob/gh-pages/master/ValidationReport.txt]
image::https://raw.githubusercontent.com/commoncriteria/fileencryption-enterprisemgmt/gh-pages/master/validation.svg[Validation]
a|[link=https://github.com/commoncriteria/fileencryption-enterprisemgmt/blob/gh-pages/master/SanityChecksOutput.md]
image::https://raw.githubusercontent.com/commoncriteria/fileencryption-enterprisemgmt/gh-pages/master/warnings.svg[SanityChecks]
a|[link=https://github.com/commoncriteria/fileencryption-enterprisemgmt/blob/gh-pages/master/SpellCheckReport.txt]
image::https://raw.githubusercontent.com/commoncriteria/fileencryption-enterprisemgmt/gh-pages/master/spell-badge.svg[SpellCheck]
a|[link=https://github.com/commoncriteria/fileencryption-enterprisemgmt/blob/gh-pages/master/TDValidationReport.txt]
image::https://raw.githubusercontent.com/commoncriteria/fileencryption-enterprisemgmt/gh-pages/master/tds.svg[TDs]
a|image::https://raw.githubusercontent.com/commoncriteria/fileencryption-enterprisemgmt/gh-pages/master/transforms.svg[transforms,150]
a| [link=https://github.com/commoncriteria/fileencryption-enterprisemgmt/blob/gh-pages/master/HTMLs.adoc]
image::https://raw.githubusercontent.com/commoncriteria/fileencryption-enterprisemgmt/gh-pages/master/html_count.svg[HTML Count]
[link=https://github.com/commoncriteria/fileencryption-enterprisemgmt/blob/gh-pages/master/PDFs.adoc]
image::https://raw.githubusercontent.com/commoncriteria/fileencryption-enterprisemgmt/gh-pages/master/pdf_count.svg[PDF Count]
| https://github.com/commoncriteria/fileencryption-enterprisemgmt/tree/release-2.0[release-2.0] 
a| https://commoncriteria.github.io/fileencryption-enterprisemgmt/release-2.0/fileencryption-enterprisemgmt-release.html[📄]
a|[link=https://github.com/commoncriteria/fileencryption-enterprisemgmt/blob/gh-pages/release-2.0/ValidationReport.txt]
image::https://raw.githubusercontent.com/commoncriteria/fileencryption-enterprisemgmt/gh-pages/release-2.0/validation.svg[Validation]
a|[link=https://github.com/commoncriteria/fileencryption-enterprisemgmt/blob/gh-pages/release-2.0/SanityChecksOutput.md]
image::https://raw.githubusercontent.com/commoncriteria/fileencryption-enterprisemgmt/gh-pages/release-2.0/warnings.svg[SanityChecks]
a|[link=https://github.com/commoncriteria/fileencryption-enterprisemgmt/blob/gh-pages/release-2.0/SpellCheckReport.txt]
image::https://raw.githubusercontent.com/commoncriteria/fileencryption-enterprisemgmt/gh-pages/release-2.0/spell-badge.svg[SpellCheck]
a|[link=https://github.com/commoncriteria/fileencryption-enterprisemgmt/blob/gh-pages/release-2.0/TDValidationReport.txt]
image::https://raw.githubusercontent.com/commoncriteria/fileencryption-enterprisemgmt/gh-pages/release-2.0/tds.svg[TDs]
a|image::https://raw.githubusercontent.com/commoncriteria/fileencryption-enterprisemgmt/gh-pages/release-2.0/transforms.svg[transforms,150]
a| [link=https://github.com/commoncriteria/fileencryption-enterprisemgmt/blob/gh-pages/release-2.0/HTMLs.adoc]
image::https://raw.githubusercontent.com/commoncriteria/fileencryption-enterprisemgmt/gh-pages/release-2.0/html_count.svg[HTML Count]
[link=https://github.com/commoncriteria/fileencryption-enterprisemgmt/blob/gh-pages/release-2.0/PDFs.adoc]
image::https://raw.githubusercontent.com/commoncriteria/fileencryption-enterprisemgmt/gh-pages/release-2.0/pdf_count.svg[PDF Count]
|===

https://github.com/commoncriteria/fileencryption-enterprisemgmt/issues[image:https://img.shields.io/github/issues/commoncriteria/fileencryption.svg?maxAge=2592000[GitHub
issues Open]]

=== Draft Version

* https://commoncriteria.github.io/fileencryption-enterprisemgmt/master/fileencryption-enterprisemgmt-release.html[PP Module for File Encryption Enterprise Management] (html)

=== Release Version

* https://www.niap-ccevs.org/protectionprofiles/521[PP Module for File Encryption Enterprise Management Version 2.0]
* https://www.niap-ccevs.org/protectionprofiles/427[PP Module for File Encryption Enterprise Management Version 1.0]

=== Contributing

If you are interested in contributing directly to future versions the
this Protection Profile, please consider joining the NIAP technical
community.
* https://www.niap-ccevs.org/technical-communities[NIAP Technical Communities]

=== Feedback

Questions, comments, and fixes can be submitted to the
https://github.com/commoncriteria/application/issues[repository issue
tracker]

=== Quickstart

To clone this project along with its _transforms_ submodule run:

....
  git clone --recursive git@github.com:commoncriteria/fileencryption-enterprisemgmt.git
....

To pull updates from the upstream _transforms_ submodule and commit them
run:

....
 git submodule update --remote transforms
 git add transforms
 git commit
....

==== Development Info

* https://github.com/commoncriteria/transforms/wiki/Working-with-Transforms-as-a-Submodule[Help
working with Transforms Submodule]

=== Repository Content

* input - Contains the `meat' of the project. It’s the input content (in
XML form) that gets transformed to readable html.
* output - The output directory where the html is placed after
transformation.
* output/images - The directory where images are stored
* transforms - Points to the transform subproject which is really a
repository for resources shared amongst many Common Criteria projects.

=== Links

* https://www.niap-ccevs.org/[National Information Assurance Partnership
(NIAP)]
* https://www.commoncriteriaportal.org/[Common Criteria Portal]

## Links 
* [National Information Assurance Partnership (NIAP)](https://www.niap-ccevs.org/)
* [Common Criteria Portal](https://www.commoncriteriaportal.org/)

## License

See [License](./LICENSE)
